// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'member_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

MemberModel _$MemberModelFromJson(Map<String, dynamic> json) => MemberModel(
  id: json['id'] as String,
  authUserId: json['auth_user_id'] as String?,
  email: json['email'] as String,
  name: json['name'] as String,
  residentId: json['resident_id'] as String,
  address: json['address'] as String,
  phone: json['phone'] as String,
  profilePhotoUrl: json['profile_photo_url'] as String?,
  companyName: json['company_name'] as String?,
  companyPosition: json['company_position'] as String?,
  companyAddress: json['company_address'] as String?,
  jobType: json['job_type'] as String?,
  hobby: json['hobby'] as String?,
  specialty: json['specialty'] as String?,
  recommender: json['recommender'] as String?,
  jcAffiliation: json['jc_affiliation'] as String?,
  memberNumber: json['member_number'] as String?,
  jcPosition: json['jc_position'] as String?,
  joinedAt: json['joined_at'] as String?,
  department: json['department'] as String?,
  transferredAt: json['transferred_at'] as String?,
  discipline: json['discipline'] as String?,
  isApproved: json['is_approved'] as bool,
  isSuspended: json['is_suspended'] as bool,
  rejectionReason: json['rejection_reason'] as String?,
  withdrawnAt: json['withdrawn_at'] == null
      ? null
      : DateTime.parse(json['withdrawn_at'] as String),
  isDeleted: json['is_deleted'] as bool,
  isSpecialMember: json['is_special_member'] as bool,
  createdAt: DateTime.parse(json['created_at'] as String),
  updatedAt: DateTime.parse(json['updated_at'] as String),
);

Map<String, dynamic> _$MemberModelToJson(MemberModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'auth_user_id': instance.authUserId,
      'email': instance.email,
      'name': instance.name,
      'resident_id': instance.residentId,
      'address': instance.address,
      'phone': instance.phone,
      'profile_photo_url': instance.profilePhotoUrl,
      'company_name': instance.companyName,
      'company_position': instance.companyPosition,
      'company_address': instance.companyAddress,
      'job_type': instance.jobType,
      'hobby': instance.hobby,
      'specialty': instance.specialty,
      'recommender': instance.recommender,
      'jc_affiliation': instance.jcAffiliation,
      'member_number': instance.memberNumber,
      'jc_position': instance.jcPosition,
      'joined_at': instance.joinedAt,
      'department': instance.department,
      'transferred_at': instance.transferredAt,
      'discipline': instance.discipline,
      'is_approved': instance.isApproved,
      'is_suspended': instance.isSuspended,
      'rejection_reason': instance.rejectionReason,
      'withdrawn_at': instance.withdrawnAt?.toIso8601String(),
      'is_deleted': instance.isDeleted,
      'is_special_member': instance.isSpecialMember,
      'created_at': instance.createdAt.toIso8601String(),
      'updated_at': instance.updatedAt.toIso8601String(),
    };

Map<String, dynamic> _$$MemberModelImplToJson(_$MemberModelImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'authUserId': instance.authUserId,
      'email': instance.email,
      'name': instance.name,
      'residentId': instance.residentId,
      'address': instance.address,
      'phone': instance.phone,
      'profilePhotoUrl': instance.profilePhotoUrl,
      'companyName': instance.companyName,
      'companyPosition': instance.companyPosition,
      'companyAddress': instance.companyAddress,
      'jobType': instance.jobType,
      'hobby': instance.hobby,
      'specialty': instance.specialty,
      'recommender': instance.recommender,
      'jcAffiliation': instance.jcAffiliation,
      'memberNumber': instance.memberNumber,
      'jcPosition': instance.jcPosition,
      'joinedAt': instance.joinedAt,
      'department': instance.department,
      'transferredAt': instance.transferredAt,
      'discipline': instance.discipline,
      'isApproved': instance.isApproved,
      'isSuspended': instance.isSuspended,
      'rejectionReason': instance.rejectionReason,
      'withdrawnAt': instance.withdrawnAt?.toIso8601String(),
      'isDeleted': instance.isDeleted,
      'isSpecialMember': instance.isSpecialMember,
      'createdAt': instance.createdAt.toIso8601String(),
      'updatedAt': instance.updatedAt.toIso8601String(),
    };
