-- ============================================
-- JC 앱 데이터베이스 스키마
-- Version: 1.0.0 (Railway)
-- Date: 2026-02-06
-- Description: Initial database schema for JC member management app
-- ============================================
--
-- 이 파일은 더 이상 사용되지 않습니다.
-- Railway PostgreSQL 환경의 정식 스키마는 ../railway_init.sql 을 참고하세요.
--
-- 프로젝트는 Railway(자체 호스팅 PostgreSQL + Node.js API)를 사용합니다.
--
-- 데이터베이스 초기화:
--   1. database/railway_init.sql 실행
--   2. database/create_admin.sql 로 관리자 계정 생성
-- ============================================
